database2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import register
from .dataentry import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")), # Don't need a view, django covers us on the functionality
    path("", views.home, name="home"),
    # This initiates the entry view
    path("settings/", views.settings, name="settings"),
    path("entry/", views.entry, name="entry"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("register/", register, name="register"),
    path("myteam/", views.myteam, name="myteam"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

database2/dataentry/models.py
from django.db import models



class Team(models.Model):
    name = models.CharField(max_length=150, unique=True)

    # Now, the names of the teams and pitchers will be displayed in the dropdowns instead of their IDs.
    def __str__(self):
        return self.name


class Pitcher(models.Model):

    # models.CASCADE means that when the referenced Team is deleted, also delete the
    # Pitcher instances that have a foreign key to them.
    team = models.ForeignKey(Team, related_name="pitchers", on_delete=models.CASCADE)
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    """A pitching session

    This can be an actual game or a bullpen session.  It's a collection of pitches for a specific date.
    """
    team = models.ForeignKey(Team, related_name="games", on_delete=models.CASCADE)
    date = models.DateField()

    def get_pitch_count(self, pitcher):
        return self.pitches.filter(pitcher=pitcher).count()


class PitchType(models.TextChoices):
    FASTBALL = "FB", "Fastball"
    CURVEBALL = "CB", "Curveball"
    CHANGEUP = "CH", "Changeup"
    SLIDER = "SL", "Slider"
    SPLITTER = "SPL", "Splitter"
    CUTTER = "CUT", "Cutter"
    KNUCK = "KN", "Knuck"
    EEPHUS = "EE", "Eephus"


class PitchResult(models.TextChoices):
    BALL = "BALL", "Ball"
    STRIKE_LOOKING = "K Looking", "Strike Looking"
    STRIKE_SWINGING = "K Swinging", "Strike Swinging"
    FOUL = "Foul Ball", "Foul Ball"
    BIP_OUT = "BIP OUT", "BIP Out"
    SINGLE = "SGL", "Single"
    DOUBLE = "DBL", "Double"
    TRIPLE = "TPL", "Triple"
    HOMER = "HR", "HR"
    HBP = "HBP", "HBP"
    DROP_3D_SAFE = "D3S", "Drop 3d & Safe"
    REACH_ON_ERROR = "ROE", "Reach on Error"


class Pitch(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    pitcher = models.ForeignKey(Pitcher, related_name="pitches", on_delete=models.CASCADE)
    # game = models.ForeignKey(Game, related_name="pitches", on_delete=models.CASCADE)
    date = models.DateField()
    pitch_type = models.CharField(max_length=5, choices=PitchType.choices)
    result = models.CharField(max_length=100, choices=PitchResult.choices)
    pitch_count = models.IntegerField()
    velo = models.DecimalField(max_digits=5, decimal_places=2)
    # timestamp = models.DateTimeField(default=timezone.now)

database2/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


# Needed to update settings for this one
class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    team = models.ForeignKey("dataentry.Team", on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.username

dataentry/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class Team(models.Model):
    name = models.CharField(max_length=150, unique=True)

    # Now, the names of the teams and pitchers will be displayed in the dropdowns instead of their IDs.
    def __str__(self):
        return self.name


class Pitcher(models.Model):

    # models.CASCADE means that when the referenced Team is deleted, also delete the
    # Pitcher instances that have a foreign key to them.
    team = models.ForeignKey(Team, related_name="pitchers", on_delete=models.CASCADE)
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Game(models.Model):
    """A pitching session

    This can be an actual game or a bullpen session.  It's a collection of pitches for a specific date.
    """
    team = models.ForeignKey(Team, related_name="games", on_delete=models.CASCADE)
    date = models.DateField()

    def get_pitch_count(self, pitcher):
        return self.pitches.filter(pitcher=pitcher).count()


class PitchType(models.TextChoices):
    FASTBALL = "FB", "Fastball"
    CURVEBALL = "CB", "Curveball"
    CHANGEUP = "CH", "Changeup"
    SLIDER = "SL", "Slider"
    SPLITTER = "SPL", "Splitter"
    CUTTER = "CUT", "Cutter"
    KNUCK = "KN", "Knuck"
    EEPHUS = "EE", "Eephus"


class PitchResult(models.TextChoices):
    BALL = "BALL", "Ball"
    STRIKE_LOOKING = "K Looking", "Strike Looking"
    STRIKE_SWINGING = "K Swinging", "Strike Swinging"
    FOUL = "Foul Ball", "Foul Ball"
    BIP_OUT = "BIP OUT", "BIP Out"
    SINGLE = "SGL", "Single"
    DOUBLE = "DBL", "Double"
    TRIPLE = "TPL", "Triple"
    HOMER = "HR", "HR"
    HBP = "HBP", "HBP"
    DROP_3D_SAFE = "D3S", "Drop 3d & Safe"
    REACH_ON_ERROR = "ROE", "Reach on Error"


class Pitch(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    pitcher = models.ForeignKey(Pitcher, related_name="pitches", on_delete=models.CASCADE)
    # game = models.ForeignKey(Game, related_name="pitches", on_delete=models.CASCADE)
    date = models.DateField()
    pitch_type = models.CharField(max_length=5, choices=PitchType.choices)
    result = models.CharField(max_length=100, choices=PitchResult.choices)
    pitch_count = models.IntegerField()
    velo = models.DecimalField(max_digits=5, decimal_places=2)
    # timestamp = models.DateTimeField(default=timezone.now)


# Needed to update settings for this one
class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.username

database2/dataentry/forms.py
from django import forms

from .models import Pitch, Pitcher


class PitcherForm(forms.ModelForm):
    class Meta:
        model = Pitcher
        fields = ["team", "name"]


class PitchForm(forms.ModelForm):
    class Meta:
        model = Pitch
        fields = ["team", "pitcher", "date", "pitch_type", "velo", "result"]

database2/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email", "team")  # Add email to the fields

database2/dataentry/views.py
from django.db.models import Max
from django.shortcuts import render, redirect

from django.contrib.auth import get_user_model

from .forms import PitchForm
from .models import Pitch, Team, Pitcher


def home(request):
    """home page"""
    context = {}  # context is where you can define variables to be used
    return render(request, "dataentry/index.html", context)



def settings(request):
    """Settings: Set your date, pitcher, and team"""
    if request.method == "POST":
        # Get the team and pitcher instances to record in the session variables
        team = Team.objects.get(id=request.POST.get("team"))
        pitcher = Pitcher.objects.get(id=request.POST.get("pitcher"))

        # Allow users to set the session variables to the names instead of the ids
        # This is so we can display the names in the entry view
        request.session["team"] = team.name
        request.session["pitcher"] = pitcher.name
        request.session["date"] = request.POST.get("date")

        # Redirect to entry page
        return redirect("entry")

    # Get the logged-in user's team and pitchers
    CustomUser = get_user_model()
    user = CustomUser.objects.get(username=request.user.username)
    teams = Team.objects.filter(id=user.team_id)
    pitchers = Pitcher.objects.filter(team_id=user.team_id)
    # print(user.team_id)
    # print(user.username)
    # If the request method is not POST (i.e., it's a GET request), render the settings page
    context = {
        "teams": teams,
        "pitchers": pitchers,
        "date": request.session.get("date", ""),
        "user": user.username,
    }

    return render(request, "dataentry/settings.html", context)


def entry(request):
    """data adding page"""
    # Get the pitcher, date, and team from the session variables
    pitcher_value = request.session.get("pitcher")
    date_value = request.session.get("date")
    team_value = request.session.get("team")

    # not sure why team_value is being rejected, but adding this extra step fixes it
    team = Team.objects.get(name=team_value)

    if request.method == "POST":
        form = PitchForm(request.POST)

        # To allow the pitcher input in the entry view to be a form input as well as a session variable changer
        # Get the pitcher instance
        pitcher = Pitcher.objects.get(id=request.POST.get("pitcher"))
        # Set the session variable to the name instead of the id
        request.session["pitcher"] = pitcher.name

        # Calculate the maximum pitch count for the specified pitcher and date so we know what to add to
        pitch_count = Pitch.objects.filter(
            pitcher=pitcher,
            date=date_value,
            team=team
        ).aggregate(Max("pitch_count"))["pitch_count__max"] or 0

        if form.is_valid():
            # Increment the "Pitch Count" field by 1
            pitch_count += 1
            form.instance.pitch_count = pitch_count
            form.save()
            return redirect("entry")  # Redirect back to the same page
    else:
        # Pre-Populate the form with the date, rest are pre-populated in html
        form = PitchForm(initial={
            "pitcher": pitcher_value,
            "team": team_value,
            "date": date_value,
        })

    # Pull in all the data (for that team and that date, for table view.)
    pitchdata = Pitch.objects.filter(team=team, date=date_value)

    # Get the logged-in user's team and pitchers
    CustomUser = get_user_model()
    user = CustomUser.objects.get(username=request.user.username)
    teams = Team.objects.filter(id=user.team_id)
    pitchers = Pitcher.objects.filter(team_id=user.team_id)

    context = {
        "team_name": team,
        "pitcher_name": pitcher_value,
        "pitchdata": pitchdata,
        "form": form,
        "teams": teams,
        "pitchers": pitchers,
    }

    # print(pitcher_value)
    return render(request, "dataentry/entry.html", context)


def dashboard(request):
    """PowerBI DashBoard"""
    context = {}  # context is where you can define variables to be used
    return render(request, "dataentry/dashboard.html", context)


def myteam(request):
    """my team page"""
    # Fetch the team associated with the logged-in user
    team = request.user.team

    # Fetch all the pitchers associated with that team
    pitchers = Pitcher.objects.filter(team=team)

    # Pass the pitchers to the context
    context = {
        "team": team,
        "pitchers": pitchers
        }

    return render(request, "dataentry/myteam.html", context)

database2/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib.auth.forms import UserCreationForm

from .forms import CustomUserCreationForm


def register(request):
    """register user page"""
    # If it's a GET request, we'll just render the form with the context here
    if request.method == "GET":
        return render(
            request, "registration/register.html",
            {"form": CustomUserCreationForm}
        )
    # If its a POST, a new custom form will be created and the new user will be saved and logged in
    # and redirected to the dashboard
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            CustomUser = form.save()
            UserCreationForm(request, CustomUser)
            return redirect(reverse("login"))

dataentry/views.py
from django.db.models import Max
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .forms import PitchForm, CustomUserCreationForm
from .models import Pitch, Team, Pitcher


def home(request):
    """home page"""
    context = {}  # context is where you can define variables to be used
    return render(request, "dataentry/index.html", context)



def settings(request):
    """Settings: Set your date, pitcher, and team"""
    if request.method == "POST":
        # Get the team and pitcher instances to record in the session variables
        team = Team.objects.get(id=request.POST.get("team"))
        pitcher = Pitcher.objects.get(id=request.POST.get("pitcher"))

        # Allow users to set the session variables to the names instead of the ids
        # This is so we can display the names in the entry view
        request.session["team"] = team.name
        request.session["pitcher"] = pitcher.name
        request.session["date"] = request.POST.get("date")

        # Redirect to entry page
        return redirect("entry")

    # Get the logged-in user's team and pitchers
    CustomUser = get_user_model()
    user = CustomUser.objects.get(username=request.user.username)
    teams = Team.objects.filter(id=user.team_id)
    pitchers = Pitcher.objects.filter(team_id=user.team_id)
    # print(user.team_id)
    # print(user.username)
    # If the request method is not POST (i.e., it's a GET request), render the settings page
    context = {
        "teams": teams,
        "pitchers": pitchers,
        "date": request.session.get("date", ""),
        "user": user.username,
    }

    return render(request, "dataentry/settings.html", context)


def entry(request):
    """data adding page"""
    # Get the pitcher, date, and team from the session variables
    pitcher_value = request.session.get("pitcher")
    date_value = request.session.get("date")
    team_value = request.session.get("team")

    # not sure why team_value is being rejected, but adding this extra step fixes it
    team = Team.objects.get(name=team_value)

    if request.method == "POST":
        form = PitchForm(request.POST)

        # To allow the pitcher input in the entry view to be a form input as well as a session variable changer
        # Get the pitcher instance
        pitcher = Pitcher.objects.get(id=request.POST.get("pitcher"))
        # Set the session variable to the name instead of the id
        request.session["pitcher"] = pitcher.name

        # Calculate the maximum pitch count for the specified pitcher and date so we know what to add to
        pitch_count = Pitch.objects.filter(
            pitcher=pitcher,
            date=date_value,
            team=team
        ).aggregate(Max("pitch_count"))["pitch_count__max"] or 0

        if form.is_valid():
            # Increment the "Pitch Count" field by 1
            pitch_count += 1
            form.instance.pitch_count = pitch_count
            form.save()
            return redirect("entry")  # Redirect back to the same page
    else:
        # Pre-Populate the form with the date, rest are pre-populated in html
        form = PitchForm(initial={
            "pitcher": pitcher_value,
            "team": team_value,
            "date": date_value,
        })

    # Pull in all the data (for that team and that date, for table view.)
    pitchdata = Pitch.objects.filter(team=team, date=date_value)

    # Get the logged-in user's team and pitchers
    CustomUser = get_user_model()
    user = CustomUser.objects.get(username=request.user.username)
    teams = Team.objects.filter(id=user.team_id)
    pitchers = Pitcher.objects.filter(team_id=user.team_id)

    context = {
        "team_name": team,
        "pitcher_name": pitcher_value,
        "pitchdata": pitchdata,
        "form": form,
        "teams": teams,
        "pitchers": pitchers,
    }

    # print(pitcher_value)
    return render(request, "dataentry/entry.html", context)


def dashboard(request):
    """PowerBI DashBoard"""
    context = {}  # context is where you can define variables to be used
    return render(request, "dataentry/dashboard.html", context)



def register(request):
    """register user page"""
    # If it's a GET request, we'll just render the form with the context here
    if request.method == "GET":
        return render(
            request, "registration/register.html",
            {"form": CustomUserCreationForm}
        )
    # If its a POST, a new custom form will be created and the new user will be saved and logged in
    # and redirected to the dashboard
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            CustomUser = form.save()
            UserCreationForm(request, CustomUser)
            return redirect(reverse("login"))


def myteam(request):
    """my team page"""
    # Fetch the team associated with the logged-in user
    team = request.user.team

    # Fetch all the pitchers associated with that team
    pitchers = Pitcher.objects.filter(team=team)

    # Pass the pitchers to the context
    context = {
        "team": team,
        "pitchers": pitchers
        }

    return render(request, "dataentry/myteam.html", context)

database2/templates/dataentry/dashboard.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/ico" sizes="64x64" href="{% static 'dataentry/img/favicon.ico' %}">
    <title>dataBase</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            text-align: center;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }
        .container {
            width: 80%; /* Adjust the width as needed */
            height: 80%; /* Adjust the height as needed */
        }
        .navbar {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
        }
        .navbar-button {
            margin: 0 10px;
            padding: 5px 10px;
            background-color: #555;
            border: none;
            color: #fff;
            cursor: pointer;
        }
        .navbar-title {
            font-size: 24px;
            font-weight: bold;
        }
        .buttons {
            display: flex;
            align-items: center;
            justify-content: start;
        }
        .buttons p {
            margin-right: auto;
        }
    </style>
</head>
<body>
    <div class="navbar">
        <div class="navbar-title">dataBase</div>
        <div class="buttons">
            <p> {{ user }} </p>
            <a href="{% url 'myteam' %}" class="navbar-button">My Team</a>
            <a href="{% url 'entry' %}" class="navbar-button">Pitch Entry</a>
        </div>
    </div>
    <div class="container">
        <iframe title="Report Section" width="1000" height="600" src="https://app.powerbi.com/view?r=eyJrIjoiMWI3NWIxMmMtYmI4OC00OTZlLThkZjQtY2E1ZWI0MGQyYTZhIiwidCI6IjRiNWQ0NWY5LTY0MTMtNGVmNS1hODFhLTIyYzRiZTM5OTYxNiJ9" frameborder="0" allowFullScreen="true">
        </iframe>
    </div>
</body>
</html>

database2/templates/dataentry/entry.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/ico" sizes="64x64" href="{% static 'dataentry/img/favicon.ico' %}">
    <title>dataBase</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .form-inputs {
            display: flex;
            justify-content: center;
            gap: 20px;
            padding: 10px;
        }
        .container {
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            text-align: center;
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: center;
            padding: 20px;
            border-radius: 5px;
            overflow: hidden;
        }
        .form {
            flex: 1;
            padding: 1px 10px; /* Adjust top and bottom padding (0px) and left and right padding (20px) */
            display: flex;
            flex-direction: column;
            font-size: 17px;
        }
        .table-container {
            flex: 1;
            background-color: #f0f0f0;
            padding: 30px;
            height: 400px; 
            width: 500px; /* Set the desired fixed height and width */
            overflow-y: auto; /* Add a vertical scrollbar when needed */
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }
        th, td {
            padding: 10px;
            text-align: center;
            white-space: nowrap;
        }
        th {
            background-color: #333;
            color: #fff;
        }
        .table-header {
            position: sticky;
            top: 0;
            background-color: #f0f0f0;
        }
        .table thead tr {
            position: sticky;
            top: 0;
            background-color: #f0f0f0;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #ddd;
        }
        h1 {
            font-size: 20px;
            margin: 0;
        }
        .navbar {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: #333; /* Change the background color as needed */
        color: #fff; /* Change the text color as needed */
        padding: 10px 20px;
        }
        /* Style for the buttons */
        .navbar-button {
            margin: 0 10px;
            padding: 5px 10px;
            background-color: #555; /* Change the button background color */
            border: none;
            color: #fff; /* Change the button text color */
            cursor: pointer;
        }
        /* Style for the "dataBase" text */
        .navbar-title {
            font-size: 24px;
            font-weight: bold;
        }
        .mainform {
            display: flex;
            flex-direction: column;
            gap: 1px;
            align-items: normal;
            padding: 10px ;
        }
        .mainform label {
            margin-bottom: 5px;
        }

        .mainform input[type="submit"] {
            margin-top: 10px;
        }
        .sessionvars {
            display: flex;
            flex-direction: column;
            gap: 10px;
            padding: 0px;
        }
        .buttons {
            display: flex;
            align-items: center;
            justify-content: start;
        }
        .buttons p {
            margin-right: auto;
        }
    </style>
</head>

<body>
<div class="navbar">
    <div class="navbar-title">dataBase</div>
        <div class="sessionvars">
            <form class="form-inputs" action="{% url 'entry' %}" method="POST">
                {% csrf_token %}
                <label for="id_team">Team:</label>
                    <select id="id_team" name="team">
                        {% for team in teams %}
                            <option value="{{ team.id }}" {% if team.id == request.session.team %}selected{% endif %}>{{ team.name }}</option>
                        {% endfor %}
                    </select>
                <!-- Pitcher select field -->
                <!--For each option in the dropdown, it checks whether the value matches the one stored in the form field (form.team.value or form.pitcher.value) or the value stored in the session variable (request.session.team or request.session.pitcher). If there's a match, that option is marked as selected.-->
                <label for="id_pitcher">Pitcher:</label>
                    <select id="id_pitcher" name="pitcher">
                        {% for pitcher in pitchers %}
                            <option value="{{ pitcher.id }}" {% if pitcher.name == request.session.pitcher %}selected{% endif %}>{{ pitcher.name }}</option>
                        {% endfor %}
                    </select>
                <div>
                    <label for="{{ form.date.id_for_label }}">Date:</label>
                        {{ form.date }}
                </div>  
            </div>
        <div class="buttons">
            <p> {{ user }} </p>
            <a href="{% url 'myteam' %}" class="navbar-button">My Team</a>
            <a href="{% url 'dashboard' %}" class="navbar-button">Dashboard</a>
        </div>
    </div>

    <div class="container">
        <div class="mainform">
            <br>
                <label>Pitch Type</label>
                {{ form.pitch_type }}
            <br>
            <br>
                <label>Velo</label>
                {{ form.velo }}
            <br>
            <br>
                <label>Result</label>
                {{ form.result }}
            <br>
            <br>
                <input type="submit" value="Submit Pitch" />
            </form>
        </div>
        <div class="table-container">
            <h2>Today's Data</h2>
                <table class="table">
                    <thead>
                        <tr class="table-header">
                            <th>Pitcher</th>
                            <th>Count</th>
                            <th>Type</th>
                            <th>Velo</th>
                            <th>Result</th>
                        </tr>
                    </thead>
                {% for instance in pitchdata %}
                    <tr>
                        <td>{{ instance.pitcher.name }}</td>
                        <td>{{ instance.pitch_count }}</td>
                        <td>{{ instance.pitch_type }}</td>
                        <td>{{ instance.velo }}</td>
                        <td>{{ instance.result }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</body>
</html>

database2/templates/dataentry/settings.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/ico" sizes="64x64" href="{% static 'dataentry/img/favicon.ico' %}">
    <title>dataBase</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            background-color: #ffffff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            text-align: center;
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: center;
            padding: 20px;
            border-radius: 5px;
            overflow: hidden;
        }
        .form {
            flex: 1;
            padding: 1px 20px; /* Adjust top and bottom padding (0px) and left and right padding (20px) */
            display: flex;
            flex-direction: column;
        }
        h1 {
            font-size: 20px;
            margin: 0;
        }
        .navbar {
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        display: flex;
        justify-content: space-between;
        align-items: center;
        background-color: #333; /* Change the background color as needed */
        color: #fff; /* Change the text color as needed */
        padding: 10px 20px;
        }
        
        /* Style for the buttons */
        .navbar-button {
            margin: 0 10px;
            padding: 5px 10px;
            background-color: #555; /* Change the button background color */
            border: none;
            color: #fff; /* Change the button text color */
            cursor: pointer;
        }

        /* Style for the "dataBase" text */
        .navbar-title {
            font-size: 24px;
            font-weight: bold;
        }
        .buttons {
            display: flex;
            align-items: center;
            justify-content: start;
        }
        .buttons p {
            margin-right: auto;
        }
        .form {
            display: flex;
            flex-direction: column;
            gap: 30px;
            padding: 10px;
        }
    </style>
</head>
<body>

<div class="navbar">
    <div class="navbar-title">dataBase</div>
    <div class="buttons">
        <p> {{ user }} </p>
        <a href="{% url 'myteam' %}" class="navbar-button">My Team</a>
        <a href="{% url 'dashboard' %}" class="navbar-button">Dashboard</a>
    </div>
</div>    
    <div class="container">
        <div class="form">
            <hp>Set your first pitcher and the date to begin tracking!</hp>
                <form method="post" id="PitchForm" action="{% url 'settings' %}">
                {% csrf_token %}
                <!--The if nothing is selected logic for pitcher returns the "Select Teamn" button. 
                The if request.session.team allows it to be recorded as a session variable as defined in the view -->
                <label for="id_team">Team:</label>
                    <select id="id_team" name="team">
                        {% for team in teams %}
                            <option value="{{ team.id }}" {% if team.id == request.session.team %}selected{% endif %}>{{ team.name }}</option>
                        {% endfor %}
                    </select>
                <label for="id_pitcher">Pitcher:</label>
                    <select id="id_pitcher" name="pitcher">
                        <option value="" {% if not request.session.team %}selected{% endif %}>Select Pitcher</option>
                        {% for pitcher in pitchers %}
                            <option value="{{ pitcher.id }}" data-team="{{ pitcher.team.id }}" {% if pitcher.id == request.session.pitcher %}selected{% endif %}>{{ pitcher.name }}</option>
                        {% endfor %}
                    </select>
                <label for="id_date">Date:</label>
                    <input type="date" id="id_date" name="date" value="{{ request.session.date }}">
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
</body>
</html>